# -*- coding: utf-8 -*-
"""uberdataanalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k0JMDHUQzENjFYJRy69YHR8BFczF--SX

**UBER DATA ANALYSIS**
We will use python to analyze data from uber.
We will use python to :


1. Check how long do people travel with Uber
2. Buisiest hour
3. Purpose of trips
4. Days with highest number of trips
5. Numbers of trips everyday
6. Trips in the month
7. The Boarding points of trips

**Importing Libraries**
"""

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import datetime 
import calendar

data = pd.read_csv('//content/UberDataset.csv')
data.head()

"""If a data is not available ,Python uses NotANumber(NaN)

**Check missing number**
"""

data.isnull()

data.isnull().any()  #all those columns that are having missing values are true and vice versa

data.isnull().sum()  #Counts all of those missing values in each column

data = data.dropna() #Dropping all NaN values

data.isnull().sum()

data.dtypes

dataset['START_DATE'] = pd.to_datetime(dataset['START_DATE'],
									errors='coerce')
dataset['END_DATE'] = pd.to_datetime(dataset['END_DATE'],
									errors='coerce')


data.dtypes

hour=[]
day=[]
dayofweek=[]
month=[]
weekday=[]

for x in data['START_DATE']:
  hour.append(x.hour)
  day.append(x.day)
  dayofweek.append(x.dayofweek)
  month.append(x.month)
  weekday.append(calendar.day_name[dayofweek[-1]])

data['HOUR'] = hour
data['DAY'] = day
data['DAY OF WEEK'] = dayofweek
data['MONTH'] = month
data['WEEKDAY'] = weekday

data.head()

"""**Categories**"""

data['CATEGORY'].value_counts()

sns.countplot(x='CATEGORY',data=data)

"""### **Check how long do people travel with Uber**"""

data['MILES'].plot.hist()

"""### **Buisiest hour**"""

hours =data['START_DATE'].dt.hour.value_counts()
hours.plot(kind='bar' , color= 'red',figsize=(10,5))

plt.xlabel('Hours')
plt.ylabel('Frequency')
plt.title('Numbers of Trips vs Hours')

"""### **Purpose of trips**"""

data['PURPOSE'].value_counts().plot(kind='bar',figsize=(10,5),color='cyan')
plt.xlabel('Purposes')
plt.ylabel('Number of Trips')
plt.title('Purposes of Trips')

"""### **Days with highest number of trips**"""

data['WEEKDAY'].value_counts().plot(kind='bar',figsize=(10,5),color='magenta')
plt.xlabel('Day')
plt.ylabel('Number of Trips')

"""### **Numbers of trips Everyday**"""

data['DAY'].value_counts().plot(kind='bar',figsize=(10,5),color='darkslategray')
plt.xlabel('Date of the Month')
plt.ylabel('Number of Trips')

"""### **Trips in the month**"""

data['MONTH'].value_counts().plot(kind='bar',figsize=(10,5),color='crimson')
plt.xlabel('Month')
plt.ylabel('Number of Trips')

"""### **The Boarding points of trips**"""

data['START'].value_counts().plot(kind='bar',figsize=(25,10),color='teal')
plt.xlabel('Boarding Point')